### ISSUE TITLE
Start fleshing milestones out in the README

### ISSUE THREAD

**Issue by ryzokuken** [osdc/community-committee#1]
The README is out, let's start a public discussion over GitHub issues and PRs and sort our initial work out.

@V1shvesh @darkHarry @saranshbarua please propose the initiatives you'll be willing to champion for and then add yourselves as team members. Also, propose ideas for projects concurrently. Make sure to mark projects you'll be willing to maintain if any.

**Comment by ryzokuken** [comment]
Umm, should I add the website design/redesign/update as a project? I'm willing to maintain it.

**Comment by saranshbarua** [comment]
I am up for the website too. We don't need to redesign it. We need to complete it.

**Comment by ryzokuken** [comment]
@saranshbarua Jekyll wasn't good enough, and we need better tooling than pure HTML/CSS/JS with Gulp magic for the long term.

I've been using Gatsby for some time, and it seems pretty good. Why not port the source in Gatsby instead?

**Comment by saranshbarua** [comment]
@ryzokuken Gatsby is awesome! I haven't worked on it yet, but this would be a good opportunity for me.
I like Jekyll as well but when it comes to choosing one of them, I'll go with gatsby.

**Comment by ryzokuken** [comment]
@saranshbarua I'm adding it as an active project then! Adding your name to maintainers.

**Comment by saranshbarua** [comment]
@ryzokuken go ahead. BTW nice work on readme.

**Comment by ryzokuken** [comment]
Closing this because it doesn't feel relevant anymore. Feel free to reopen.
