### ISSUE TITLE
Proposing Connect4 game, designed in Python & Pygame. 

### ISSUE THREAD

**Issue by bymayanksingh** [osdc/community-committee#10]
What is it?
Connect Four is a two-player connection game in which the players first choose a color and then take turns dropping one colored disc from the top into a seven-column, six-row vertically suspended grid. The pieces fall straight down, occupying the lowest available space within the column. The objective of the game is to be the first to form a horizontal, vertical, or diagonal line (+ve, -ve) of four of one's own discs. 

Repository Link: https://github.com/code-monk08/Connect-Four
Author: @code-monk08 

Currently, the Implementation of this game is based only for two players, there are a lot of improvements which can be made to the game, a few features which can be added are:

- Restructuring & Refactoring the Code. (top priority)
- Adding sockets to make it multiplayer over the same network.
- Making Game AI
- ScreenShot Feature (Window) (low priority)
- Writing Unit Test for the Game. 
- Making a Score Board/ Taking Input of Names of both players.
- we can try to implement Connect 5 ( Board Size different ) 
- Adding Comments to the code (following style guide) 
- Make an Option to choose various themes in the Game.
- Improving the Readme of the Project.

**Comment by darkHarry** [comment]
@ryzokuken let's port it here. It will be a great experience for new pythoners and would create a pool of FTOs.

**Comment by ryzokuken** [comment]
I think @code-monk08 will have to transfer the repo.

**Comment by bymayanksingh** [comment]
this is what I receive when trying to tranfer to OSDC "You don’t have the permission to create repositories on osdc"

**Comment by ryzokuken** [comment]
@code-monk08 can you add me as admin/collaborator to the repo? I can transfer it then.

**Comment by ryzokuken** [comment]
Also, are you sure you want to stick to the GPL license? We use the MIT license, but we could talk about that if you have a preference.

**Comment by ayushnagar123** [comment]
@ryzokuken i guess only owner can. Not even colaborator. By the way won't it be better to import the project:-
- It will not affect his ownership rights as he is the main head of the project and not the member of osdc so i guess he cannot have the control over the project himself.
- He cannot assign colaborators by himself which could only be done by tc and cc members.

**Comment by bymayanksingh** [comment]
@ryzokuken Yes, you can import the repository itself, Just give the ownership to OSDC while importing.

URL for my repo: https://github.com/code-monk08/Connect-Four (also mentioned above)

**Comment by bymayanksingh** [comment]
coming to the license, yes I switched to MIT license.

**Comment by ryzokuken** [comment]
@code-monk08 great, give me admin access temporarily so that I can move the repo to OSDC org. Then I guess I'll have to give you push access to it again.

**Comment by ryzokuken** [comment]
@code-monk08 You need to give me "admin" level privileges 😅

**Comment by bymayanksingh** [comment]
Yes I did that too, kindly check it. 
![image](https://user-images.githubusercontent.com/19390263/52164972-4dd8c780-2720-11e9-9aa6-2c80fcff39a5.png)

**Comment by ryzokuken** [comment]
For some reason, I still cannot see the settings panel to make the transfer at https://github.com/code-monk08/Connect-Four

**Comment by ayushnagar123** [comment]
@ryzokuken you need not to be admin to import his project if it is public project. You just need to select import repository below your new repository option, select owner as osdc, copy url, name the repository and just import it.

**Comment by bymayanksingh** [comment]
@ryzokuken that "importing" thing, is it not working? I tried the same process of importing some other repository in rapport4 organisation which I created in the past, It was fine for me.

**Comment by ryzokuken** [comment]
Oh, I didn't try that. I was planning to normally transfer the whole repo to the org, it brings all the issues, PRs etc with itself.

**Comment by bymayanksingh** [comment]
Alright, well currently I don't have issues/PR, I plan to create them when the project is in OSDC org itself.

**Comment by ayushnagar123** [comment]
If you consider to keep them in sync we can fork it too.

**Comment by bymayanksingh** [comment]
do you mean sync? well, the primary changes will take place in here itself, fork it once it's here.
