### ISSUE TITLE
Call for writing blogs

### ISSUE THREAD

**Issue by sidntrivedi** [osdc/community-committee#13]
*  [OSDC's blog website](https://osdc.github.io/blog/) has not been updated since the first 2 meetups. Thus, would like to post this open initiative to everyone (even the freshers) to write blogs for each meetup organized by the community.

* Requesting to post the links of these blogs on OSDC's Facebook Page and OSDC's Medium Channel so that the writer may find his work fruitful. The Medium posting can be automated when the discussed script gets ready.

* Those interested can append their name to a checklist made here. With one having written the blog, his name's checkbox will get ticked. When the whole list gets completed all the checkboxes will be unchecked again and the cycle loop continues.

* There may be a doubt that the checkboxes can be ticked and unticked without anyone knowing who did it. We can make the list in README and when the supposed writer writes the blog, he should make a PR to make a tick in front of his name like this:   `- [x] this is a complete item.` 

* Also if someone wants to write blog on his own topic(which should be related to tech/open-source), he can write freely and get his name appended and checked. The checking of names every time will not be made until a PR has been made to comm comm as well the blog repo.

* One who writes blog will be eligible for some extra swags.

@ryzokuken @darkHarry @saranshbarua  @vaibhavk @V1shvesh What do you think?

**Comment by ryzokuken** [comment]
@sidntrivedi012 Please don't use a hashtag in the title. Use a label instead.

**Comment by nightwarriorftw** [comment]
@sidntrivedi012  It's a good approach.
