### ISSUE TITLE
 .

### ISSUE THREAD

**Issue by Yayady1999** [osdc/community-committee#15]
I was really moved with the working and the idea of the organisation that I would like to join it. I will do my best to contribute to make the org better, so I request you to invite me.
There were also a couple of repos that I would improve and many more to contribute, so I look forward to your reply

**Name** :    Yayady
**Github** :   Yayady1999
**Email** :    yayady1999@gmail.com

**Comment by ryzokuken** [comment]
@Yayady1999 sorry, but you'd need to get involved in OSDC through regular means to get an invite to the GitHub org.
